# Generated by Django 5.2.5 on 2025-11-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان دسته\u200cبندی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی سوالات',
                'verbose_name_plural': 'دسته\u200cبندی سوالات',
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('category__order', 'order'), 'verbose_name': 'سؤال', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سؤال'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faq.faqcategory', verbose_name='دسته\u200cبندی'),
        ),
    ]
