# Generated by Django 5.2.5 on 2025-10-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_passwordlock_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], null=True, verbose_name='روز تولد'),
        ),
        migrations.AddField(
            model_name='profile',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='ماه تولد'),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال تولد'),
        ),
    ]
