# Generated by Django 5.2.5 on 2025-10-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_day_profile_month_profile_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
