# Generated by Django 5.2.5 on 2025-11-05 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('exclusive', models.BooleanField(default=False)),
                ('channel', models.CharField(default='web', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('percent_off', 'درصدی'), ('amount_off', 'مبلغ ثابت'), ('free_shipping', 'ارسال رایگان')], max_length=24)),
                ('scope', models.CharField(choices=[('line', 'سطر'), ('cart', 'سبد'), ('shipping', 'ارسال')], default='line', max_length=16)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='promos.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit_total', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product_in', 'محصول مشخص'), ('category_in', 'عضویت در دسته'), ('cart_min_total', 'حداقل مبلغ سبد'), ('qty_at_least', 'حداقل تعداد یک سطر')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='promos.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_key', models.CharField(blank=True, max_length=191, null=True)),
                ('status', models.CharField(choices=[('reserved', 'رزروشده'), ('consumed', 'مصرف\u200cشده'), ('canceled', 'لغوشده')], default='reserved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='promos.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'consumed'])), fields=('coupon', 'user'), name='uniq_coupon_user_active'), models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'consumed'])), fields=('coupon', 'guest_key'), name='uniq_coupon_guest_active')],
            },
        ),
    ]
