# Generated by Django 5.2.5 on 2025-11-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='kind',
            field=models.CharField(choices=[('product_in', 'محصول مشخص'), ('category_in', 'عضویت در دسته'), ('cart_min_total', 'حداقل مبلغ سبد'), ('qty_at_least', 'حداقل تعداد یک سطر'), ('variant_in', 'واریانت مشخص'), ('brand_in', 'برند مشخص')], max_length=32),
        ),
    ]
