# Generated by Django 5.2.5 on 2025-11-17 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0002_alter_rule_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان / توضیح کوتاه')),
                ('position', models.CharField(choices=[('hero', 'بنر بزرگ بالای صفحه'), ('strip', 'نوار وسط صفحه'), ('sidebar', 'بنر سایدبار')], default='hero', max_length=20, verbose_name='محل نمایش')),
                ('image', models.ImageField(upload_to='promos/banners/', verbose_name='تصویر دسکتاپ')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='promos/banners/', verbose_name='تصویر موبایل')),
                ('link_url', models.URLField(blank=True, max_length=500, verbose_name='لینک مقصد (لندینگ جشنواره)')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='متن دکمه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع نمایش بنر')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان نمایش بنر')),
                ('channel', models.CharField(default='web', max_length=24, verbose_name='کانال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='promos.campaign', verbose_name='کمپین مرتبط')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
            },
        ),
    ]
