# Generated by Django 5.2.5 on 2025-11-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0003_promobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='stack_with_sales',
            field=models.BooleanField(default=False, help_text='اگر غیرفعال باشد، این کوپن فقط روی کالاهایی اعمال می\u200cشود که قبلاً تخفیف دیگری نگرفته\u200cاند.', verbose_name='تجمیع با تخفیف\u200cهای دیگر'),
        ),
    ]
