# Generated by Django 5.2.5 on 2025-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0004_coupon_stack_with_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='limit_products',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='product_filter',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='slot',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='جایگاه داخل گرید (left_top, left_bottom, middle, right)'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='position',
            field=models.CharField(choices=[('hero', 'بنر بزرگ بالای صفحه'), ('strip', 'نوار وسط صفحه'), ('sidebar', 'بنر سایدبار'), ('home_grid', 'گرید بنرهای صفحه اصلی'), ('daily_deal', 'پیشنهاد روزانه'), ('deal_side', 'بنر کنار پیشنهاد روزانه')], default='hero', max_length=20, verbose_name='محل نمایش'),
        ),
    ]
