# Generated by Django 5.2.5 on 2025-12-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0005_promobanner_limit_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='priority',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='اولویت نمایش (کمتر = بالاتر)'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='slot',
            field=models.CharField(blank=True, choices=[('', '—'), ('left_top', 'چپ بالا'), ('left_bottom', 'چپ پایین'), ('middle', 'وسط'), ('right', 'راست')], default='', max_length=30, verbose_name='جایگاه داخل گرید'),
        ),
        migrations.AddIndex(
            model_name='promobanner',
            index=models.Index(fields=['position', 'channel', 'is_active'], name='promos_prom_positio_d52997_idx'),
        ),
        migrations.AddIndex(
            model_name='promobanner',
            index=models.Index(fields=['starts_at', 'ends_at'], name='promos_prom_starts__98eace_idx'),
        ),
    ]
