# Generated by Django 5.2.5 on 2025-12-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0006_promobanner_priority_alter_promobanner_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
