# Generated by Django 5.2.5 on 2025-12-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0007_promobanner_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobanner',
            name='slot',
            field=models.CharField(blank=True, choices=[('', '—'), ('left', 'چپ'), ('right', 'راست'), ('top', 'بالا'), ('bottom', 'پایین')], default='', max_length=30, verbose_name='جایگاه داخل گرید'),
        ),
    ]
