# Generated by Django 5.2.5 on 2025-12-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0008_alter_promobanner_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobanner',
            name='position',
            field=models.CharField(choices=[('hero', 'بنر بزرگ بالای صفحه'), ('strip', 'نوار وسط صفحه'), ('sidebar', 'بنر سایدبار'), ('home_grid', 'گرید بنرهای صفحه اصلی'), ('daily_deal', 'پیشنهاد روزانه'), ('deal_side', 'بنر کنار پیشنهاد روزانه'), ('home_festival_hero', 'بنر جشنواره (کانت\u200cداون/دیفالت)')], default='hero', max_length=20, verbose_name='محل نمایش'),
        ),
    ]
