# Generated by Django 5.2.5 on 2026-01-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0009_alter_promobanner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobanner',
            name='limit_products',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
