# Generated by Django 5.2.5 on 2026-01-03 18:48

from django.db import migrations

def fix_null_limit_products(apps, schema_editor):
    PromoBanner = apps.get_model("promos", "PromoBanner")
    PromoBanner.objects.filter(limit_products__isnull=True).update(limit_products=0)

class Migration(migrations.Migration):

    dependencies = [
        ("promos", "0010_alter_promobanner_limit_products"),
    ]

    operations = [
        migrations.RunPython(fix_null_limit_products, migrations.RunPython.noop),
    ]