version: "3.8"
services:
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "no", "--save", ""]
    ports:
      - "127.0.0.1:6379:6379"   # فقط لوکال، امن‌تر
    restart: unless-stopped
