# Generated by Django 5.2.5 on 2025-11-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_comment_ip_address_comment_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
    ]
