# Generated by Django 5.2.5 on 2025-11-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
