# Generated by Django 5.2.5 on 2025-11-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_likedislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
