# Generated by Django 5.2.5 on 2025-12-04 13:49
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='درباره ما', max_length=200)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('vision_title', models.CharField(default='دید ما', max_length=200)),
                ('vision_text', models.TextField(null=True, blank=True)),
                ('mission_title', models.CharField(default='ماموریت ما', max_length=200)),
                ('mission_text', models.TextField(null=True, blank=True)),
                ('who_title', models.CharField(default='ما که هستیم', max_length=200)),
                ('who_lead', models.CharField(blank=True, max_length=255, null=True)),
                ('who_text', models.TextField(null=True, blank=True)),
                ('who_image_front', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('who_image_back', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('brands_text', models.TextField(null=True, blank=True)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
