# Generated by Django 5.2.5 on 2025-12-04 14:39


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='brands_text',
            field=models.TextField(null=True, blank=True, verbose_name='متن برندها'),
        ),
        migrations.AlterField(
            model_name='about',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='تصویر هدر'),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission_text',
            field=models.TextField(null=True, blank=True, verbose_name='متن ماموریت ما'),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission_title',
            field=models.CharField(default='ماموریت ما', max_length=200, verbose_name='عنوان ماموریت ما'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='درباره ما', max_length=200, verbose_name='عنوان صفحه درباره ما'),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision_text',
            field=models.TextField(null=True, blank=True, verbose_name='متن دید ما'),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision_title',
            field=models.CharField(default='دید ما', max_length=200, verbose_name='عنوان دید ما'),
        ),
        migrations.AlterField(
            model_name='about',
            name='who_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='تصویر عقب درباره ما'),
        ),
        migrations.AlterField(
            model_name='about',
            name='who_image_front',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='تصویر جلو درباره ما'),
        ),
        migrations.AlterField(
            model_name='about',
            name='who_lead',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='متن پیش\u200cرو درباره ما'),
        ),
        migrations.AlterField(
            model_name='about',
            name='who_text',
            field=models.TextField(null=True, blank=True, verbose_name='متن ما که هستیم'),
        ),
        migrations.AlterField(
            model_name='about',
            name='who_title',
            field=models.CharField(default='ما که هستیم', max_length=200, verbose_name='عنوان ما که هستیم'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام عضو تیم')),
                ('role', models.CharField(max_length=200, verbose_name='سمت')),
                ('bio', models.TextField(null=True, blank=True, verbose_name='بیوگرافی کوتاه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='تصویر')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فیسبوک')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='Core.about')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
            },
        ),
    ]
