# Generated by Django 5.2.5 on 2025-12-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_alter_about_brands_text_alter_about_header_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برند')),
                ('logo', models.ImageField(upload_to='brands/', verbose_name='لوگو برند')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک وبسایت برند')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='Core.about')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
    ]
