# Generated by Django 5.2.5 on 2025-12-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='متا دیسکریپشن (SEO)'),
        ),
        migrations.AddField(
            model_name='about',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='متا تایتل (SEO)'),
        ),
    ]
