# Generated by Django 5.2.5 on 2025-12-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_about_meta_description_about_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='نام مجموعه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات درباره مجموعه')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='ساعت کاری')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='شماره تماس')),
                ('phone_number2', models.CharField(blank=True, max_length=11, verbose_name='شماره تماس دوم')),
                ('phone_number3', models.CharField(blank=True, max_length=11, verbose_name='شماره تماس سوم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=450, verbose_name='آدرس دقیق')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('whatsapp', models.URLField(blank=True, verbose_name='واتساپ')),
                ('twitter', models.URLField(blank=True, verbose_name='توییتر')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
    ]
