# Generated by Django 5.2.5 on 2025-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='logo_site',
            field=models.ImageField(blank=True, null=True, upload_to='site_info/', verbose_name='لوگو سایت'),
        ),
    ]
