# Generated by Django 5.2.5 on 2026-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_siteinfo_logo_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='brands_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن برندها'),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن ماموریت ما'),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن دید ما'),
        ),
        migrations.AlterField(
            model_name='about',
            name='who_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن ما که هستیم'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی کوتاه'),
        ),
    ]
