# Generated by Django 5.2.5 on 2025-12-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='تماس با ما', max_length=120, verbose_name='عنوان')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='متا تایتل (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='متا دیسکریپشن (SEO)')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='contact/', verbose_name='تصویر هدر')),
                ('intro_text', models.TextField(blank=True, null=True, verbose_name='متن معرفی کوتاه')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
    ]
