# Generated by Django 5.2.5 on 2025-12-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'قوانین و مقررات', 'verbose_name_plural': ' قوانین و مقررات'},
        ),
    ]
