# Generated by Django 5.2.5 on 2025-12-16 15:42

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_termsandconditions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(max_length=100, verbose_name='عنوان کوچک')),
                ('title_big', models.CharField(max_length=150, verbose_name='عنوان بزرگ')),
                ('background_image', models.ImageField(upload_to='home/banner/images/', verbose_name='تصویر بک\u200cگراند')),
                ('video_file', models.FileField(upload_to='home/banner/videos/', validators=[home.models.validate_video], verbose_name='ویدیو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بنر ویدیویی صفحه اصلی',
                'verbose_name_plural': 'بنر ویدیویی صفحه اصلی',
            },
        ),
    ]
