# Generated by Django 5.2.5 on 2025-12-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_promobanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoBanner',
        ),
    ]
