# Generated by Django 5.2.5 on 2025-12-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homevideobanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homevideobanner',
            name='background_image',
        ),
    ]
