# Generated by Django 5.2.5 on 2025-12-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homevideobanner_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevideobanner',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/banner/images/', verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='homevideobanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
