# Generated by Django 5.2.5 on 2025-12-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_promobanner'),
        ('home', '0005_homevideobanner_banner_image_and_more'),
    ]

    operations = [
    ]
