# Generated by Django 5.2.5 on 2025-12-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20251219_1719'),
        ('products', '0011_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBrandBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='تیتر')),
                ('subtitle', models.CharField(blank=True, max_length=120, verbose_name='زیرتیتر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/banners/', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='برند')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='دسته\u200cبندی (اختیاری)')),
            ],
            options={
                'verbose_name': 'بنر برند صفحه اصلی',
                'verbose_name_plural': 'بنرهای برند صفحه اصلی',
                'ordering': ['position', '-id'],
            },
        ),
    ]
