# Generated by Django 5.2.5 on 2025-12-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homebrandbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homevideobanner',
            name='banner_image',
        ),
    ]
