# Generated by Django 5.2.5 on 2026-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homevideobanner_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
    ]
