# Generated by Django 5.2.5 on 2025-10-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='پلاک'),
        ),
        migrations.AddField(
            model_name='address',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='واحد'),
        ),
    ]
