# Generated by Django 5.2.5 on 2025-12-01 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_address_number_address_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('carrier', models.CharField(choices=[('post', 'پست'), ('tipax', 'تیپاکس'), ('courier', 'پیک / ارسال درون\u200cشهری'), ('custom', 'سفارشی')], default='post', max_length=20, verbose_name='نوع سرویس\u200cدهنده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, help_text='هزینه ثابت که به همه سفارش\u200cها اضافه می\u200cشود (اختیاری).', max_digits=12, verbose_name='هزینه ثابت پایه (تومان)')),
                ('max_weight_grams', models.PositiveIntegerField(blank=True, help_text='اگر خالی باشد، محدودیت وزنی ندارد.', null=True, verbose_name='حداکثر وزن مجاز (گرم)')),
                ('estimated_min_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل روز تحویل')),
                ('estimated_max_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر روز تحویل')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محدوده')),
                ('provinces', models.TextField(blank=True, help_text='مثال: تهران, البرز, قزوین', verbose_name='استان\u200cها (لیست جدا شده با کاما)')),
                ('cities', models.TextField(blank=True, help_text='مثال: تهران, کرج, قم', verbose_name='شهرها (لیست جدا شده با کاما)')),
                ('is_rest_of_country', models.BooleanField(default=False, help_text='اگر فعال باشد، برای آدرس\u200cهایی که در لیست استان/شهر سایر زون\u200cها نیستند، این زون اعمال می\u200cشود.', verbose_name='شامل سایر مناطق؟')),
            ],
            options={
                'verbose_name': 'زون ارسال',
                'verbose_name_plural': 'زون\u200cهای ارسال',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_min', models.PositiveIntegerField(default=0, verbose_name='حداقل وزن (گرم)')),
                ('weight_max', models.PositiveIntegerField(blank=True, help_text='اگر خالی باشد یعنی تا بی\u200cنهایت.', null=True, verbose_name='حداکثر وزن (گرم)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='هزینه ثابت برای این بازه وزن (تومان)')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod', verbose_name='روش ارسال')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone', verbose_name='زون')),
            ],
            options={
                'verbose_name': 'تعرفه ارسال',
                'verbose_name_plural': 'تعرفه\u200cهای ارسال',
                'ordering': ('method', 'zone', 'weight_min'),
                'constraints': [models.UniqueConstraint(fields=('method', 'zone', 'weight_min', 'weight_max'), name='uniq_method_zone_weight_range')],
            },
        ),
    ]
