# Generated by Django 5.2.5 on 2025-12-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_address_number_address_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('carrier', models.CharField(choices=[('post', 'پست'), ('tipax', 'تیپاکس'), ('courier', 'پیک / ارسال درون\u200cشهری'), ('custom', 'سفارشی')], default='post', max_length=20, verbose_name='نوع سرویس\u200cدهنده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, help_text='هزینه ثابت که به همه سفارش\u200cها اضافه می\u200cشود (اختیاری).', max_digits=12, verbose_name='هزینه ثابت پایه (تومان)')),
                ('max_weight_grams', models.PositiveIntegerField(blank=True, help_text='اگر خالی باشد، محدودیت وزنی ندارد.', null=True, verbose_name='حداکثر وزن مجاز (گرم)')),
                ('estimated_min_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل روز تحویل')),
                ('estimated_max_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر روز تحویل')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
    ]
