# Generated by Django 5.2.5 on 2025-12-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shippingmethod_shippingzone_alter_address_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingRate',
        ),
        migrations.DeleteModel(
            name='ShippingZone',
        ),
    ]
