# Generated by Django 5.2.5 on 2025-12-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shippingmethod_alter_address_created_at_and_more'),
        ('shipping', '0004_delete_shippingrate_delete_shippingzone'),
    ]

    operations = [
    ]
