# Generated by Django 5.2.5 on 2025-12-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_merge_20251204_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.UUIDField(verbose_name='شناسه فروشگاه در تاپین')),
                ('from_province_id', models.IntegerField(verbose_name='استان مبدا (تاپین)')),
                ('from_city_id', models.IntegerField(verbose_name='شهر مبدا (تاپین)')),
                ('default_box_id', models.IntegerField(verbose_name='شناسه باکس پیش\u200cفرض پست')),
                ('tipax_shop_id', models.UUIDField(blank=True, null=True, verbose_name='شناسه فروشگاه تیپاکس')),
                ('tipax_product_type_id', models.IntegerField(default=0)),
                ('tipax_packing_type_id', models.IntegerField(default=0)),
                ('tipax_payment_type', models.IntegerField(default=1)),
                ('tipax_service_type', models.IntegerField(default=1)),
                ('tipax_delivery_type', models.IntegerField(default=1)),
                ('tipax_pickup_type', models.IntegerField(default=1)),
                ('api_token', models.CharField(blank=True, max_length=255, verbose_name='توکن API تاپین')),
            ],
            options={
                'verbose_name': 'تنظیمات تاپین',
                'verbose_name_plural': 'تنظیمات تاپین',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='tapin_city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='tapin_province_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='tapin_post_service_type',
            field=models.IntegerField(blank=True, choices=[(0, 'پست سفارشی'), (1, 'پست پیشتاز')], help_text='برای پست سفارشی ۰ و برای پیشتاز ۱ (مطابق مستندات تاپین).', null=True, verbose_name='نوع سرویس پست در تاپین'),
        ),
    ]
