# Generated by Django 5.2.5 on 2025-12-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_tapinconfig_address_tapin_city_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TapinConfig',
        ),
        migrations.RemoveField(
            model_name='address',
            name='tapin_city_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='tapin_province_id',
        ),
    ]
