# Generated by Django 5.2.5 on 2025-11-23 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_service_productservice_categoryservice_serviceprice'),
        ('shipping', '0002_address_number_address_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('canceled', 'لغو شده'), ('refunded', 'بازپرداخت شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('fulfillment_status', models.CharField(choices=[('new', 'جدید'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('returned', 'مرجوع شده')], default='new', max_length=20, verbose_name='وضعیت ارسال')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='جمع کل قبل تخفیف')),
                ('total_discount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='جمع تخفیف')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مبلغ نهایی')),
                ('payment_ref', models.CharField(blank=True, max_length=120, null=True, verbose_name='کد مرجع پرداخت')),
                ('payment_gateway', models.CharField(blank=True, max_length=50, null=True, verbose_name='درگاه پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shipping.address', verbose_name='آدرس ارسال')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='قیمت واحد')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='تخفیف ردیف')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='جمع ردیف')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='نام محصول (اسنپ\u200cشات)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant', verbose_name='واریانت')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
