# Generated by Django 5.2.5 on 2025-12-01 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shipping', '0003_shippingmethod_shippingzone_alter_address_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=120)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هزینه ارسال')),
                ('cart_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع سبد')),
                ('payable_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ پرداختی')),
                ('step', models.CharField(default='address', max_length=20, verbose_name='مرحله چک\u200cاوت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.address', verbose_name='آدرس انتخاب\u200cشده')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shippingmethod', verbose_name='روش ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drafts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیش\u200cنویس سفارش',
                'verbose_name_plural': 'پیش\u200cنویس\u200cهای سفارش',
            },
        ),
    ]
