# Generated by Django 5.2.5 on 2025-12-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdraft'),
        ('shipping', '0003_shippingmethod_shippingzone_alter_address_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.shippingmethod', verbose_name='روش ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه ارسال'),
        ),
    ]
