# Generated by Django 5.2.5 on 2025-12-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_method_order_shipping_price_and_more'),
        ('orders', '0003_order_shipping_method_order_shipping_price'),
    ]

    operations = [
    ]
