# Generated by Django 5.2.5 on 2025-12-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_fulfillment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('new', 'جدید'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('returned', 'مرجوع شده'), ('send-canceled', 'لغو ارسال')], default='new', max_length=20, verbose_name='وضعیت ارسال'),
        ),
    ]
