# Generated by Django 5.2.5 on 2025-08-28 14:12

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import mptt.fields
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام ویژگی')),
                ('code', models.SlugField(max_length=120, unique=True, verbose_name='کُد ویژگی')),
                ('kind', models.CharField(choices=[('text', 'متن'), ('int', 'عدد صحیح'), ('decimal', 'عدد اعشاری'), ('bool', 'بلی/خیر'), ('choice', 'گزینشی (تکی)'), ('multi', 'گزینشی (چندتایی)')], default='text', max_length=10, verbose_name='نوع')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد (مثلاً g, cm)')),
                ('is_variant', models.BooleanField(default=False, verbose_name='تأثیر روی واریانت؟')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='اولویت نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['is_active'], name='products_at_is_acti_1bef44_idx'), models.Index(fields=['position'], name='products_at_positio_8287f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(max_length=120, verbose_name='مقدار (کُد)')),
                ('label', models.CharField(max_length=120, verbose_name='برچسب نمایشی')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='اولویت')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='products.attribute', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'گزینهٔ ویژگی',
                'verbose_name_plural': 'گزینه\u200cهای ویژگی',
                'ordering': ('attribute', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=160, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='موقعیت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='الزامی؟')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='اولویت')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='products.attribute', verbose_name='ویژگی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='products.category', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'ویژگیِ دسته',
                'verbose_name_plural': 'ویژگی\u200cهای دسته',
                'ordering': ('category', 'position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='categories', through='products.CategoryAttribute', to='products.attribute', verbose_name='ویژگی\u200cها'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رنگ')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='اسلاگ')),
                ('hex_code', colorfield.fields.ColorField(default='#6B7280', image_field=None, max_length=25, samples=['#000000', '#FFFFFF', '#FF0000', '#00FF00', '#0000FF', '#F59E0B', '#10B981', '#06B6D4', '#6366F1'], verbose_name='کد رنگ')),
                ('swatch_image', models.ImageField(blank=True, null=True, upload_to='colors/', verbose_name='تصویر سواچ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active'], name='products_co_is_acti_3a9424_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='نام محصول')),
                ('slug', models.SlugField(blank=True, max_length=230, unique=True, verbose_name='اسلاگ')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='برند')),
                ('short_description', models.CharField(blank=True, max_length=280, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت قبلی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pub', 'منتشر شده'), ('arch', 'آرشیو')], default='draft', max_length=5, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='ویژگی\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, verbose_name='متن')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='عدد صحیح')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='عدد اعشاری')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='بلی/خیر')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='products.product', verbose_name='محصول')),
                ('value_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_values_single', to='products.attributechoice', verbose_name='گزینه (تکی)')),
                ('values_multi', models.ManyToManyField(blank=True, related_name='product_values_multi', to='products.attributechoice', verbose_name='گزینه\u200cها (چندتایی)')),
            ],
            options={
                'verbose_name': 'مقدار ویژگیِ محصول',
                'verbose_name_plural': 'مقادیر ویژگی\u200cهای محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_image_upload_to, verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=120, verbose_name='متن جایگزین')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='اولویت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='products.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'گالری تصاویر',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='سایز/مدل')),
                ('sku', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='SKU باید 3 تا 32 کاراکتر، فقط حروف بزرگ، اعداد و - _ . باشد.', regex='^[A-Z0-9\\-_\\.]{3,32}$')], verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='بارکد')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واریانت')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'واریانت',
                'verbose_name_plural': 'واریانت\u200cها',
            },
        ),
        migrations.AddConstraint(
            model_name='attributechoice',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='uniq_attr_value'),
        ),
        migrations.AddConstraint(
            model_name='categoryattribute',
            constraint=models.UniqueConstraint(fields=('category', 'attribute'), name='uniq_category_attribute'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'position'], name='products_ca_parent__d34eab_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'parent'], name='products_ca_slug_08dca6_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='uniq_sibling_slug'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('parent_id')), _negated=True), name='no_self_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['product', 'attribute'], name='products_pr_product_c00cf1_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute'), name='uniq_product_attribute'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'color'], name='products_pr_product_f69c2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='uniq_primary_image_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'position'), name='uniq_product_image_position'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'color'], name='products_pr_product_dc301d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_9d6315_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='uniq_product_color_size'),
        ),
    ]
