# Generated by Django 5.2.5 on 2025-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_brand_brand_product_brand_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, related_name='products_extra', to='products.category', verbose_name='دسته\u200cهای دیگر'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand_fk'], name='products_pr_brand_f_c33378_idx'),
        ),
    ]
