# Generated by Django 5.2.5 on 2025-10-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_additional_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'rank', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SizeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='uniq_product_color_size',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_product_dc301d_idx',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.size', verbose_name='سایز'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'color', 'size'], name='products_pr_product_96c55c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('size__isnull', False)), fields=('product', 'color', 'size'), name='uniq_prod_color_size_when_size_not_null'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('size__isnull', True)), fields=('product', 'color'), name='uniq_prod_color_when_size_null'),
        ),
        migrations.AddField(
            model_name='size',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.sizegroup'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_group',
            field=models.ForeignKey(blank=True, help_text='اگر تنظیم شود، محصولات این دسته به\u200cطور پیش\u200cفرض از این گروه سایز استفاده می\u200cکنند.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='products.sizegroup', verbose_name='گروه سایز'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['size_group'], name='products_ca_size_gr_b7ff85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('group', 'code')},
        ),
    ]
