# Generated by Django 5.2.5 on 2025-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_size_sizegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='spec_slots',
            field=models.JSONField(blank=True, default=list, help_text='لیست آیتم\u200cها به ترتیب نمایش. مثال: [ {"key":"brand","label":"برند"}, {"key":"attr:os","label":"سیستم\u200cعامل"}, {"key":"attr:model_name","label":"مدل"}, {"key":"attr:storage","label":"ظرفیت حافظه"}, {"key":"attr:display_size","label":"اندازه صفحه\u200cنمایش"}, {"key":"attr:battery_capacity","label":"ظرفیت باتری"} ]'),
        ),
    ]
