# Generated by Django 5.2.5 on 2025-10-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_spec_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_active',
            field=models.BooleanField(default=False, verbose_name='تخفیف محصول فعال'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اگر پر شد، مبلغ ثابت از قیمت پایه کم می\u200cشود.', max_digits=12, null=True, verbose_name='مبلغ ثابت تخفیف (تومان)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اگر پر شد، درصدی از قیمت پایه کم می\u200cشود.', max_digits=5, null=True, verbose_name='درصد تخفیف (مثلاً 10 برای 10%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع تخفیف'),
        ),
    ]
