# Generated by Django 5.2.5 on 2025-10-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sale_active_product_sale_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sale_active_variant',
            field=models.BooleanField(default=False, verbose_name='تخفیف روی این واریانت فعال'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sale_amount_variant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مثلاً 10000 (تومان) (اختیاری)', max_digits=12, null=True, verbose_name='مبلغ ثابت تخفیف واریانت'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sale_percent_variant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مثلاً 10 برای 10% (اختیاری)', max_digits=5, null=True, verbose_name='درصد تخفیف واریانت'),
        ),
    ]
