# Generated by Django 5.2.5 on 2025-10-26 11:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariant_sale_active_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=160, verbose_name='عنوان')),
                ('kind', models.CharField(choices=[('install', 'نصب و راه\u200cاندازی'), ('warranty', 'گارانتی/بیمه افزوده'), ('custom', 'سفارشی')], default='install', max_length=20, verbose_name='نوع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('exclusive_group', models.CharField(blank=True, max_length=60, verbose_name='گروه انحصاری')),
                ('per_item', models.BooleanField(default=True, verbose_name='به ازای هر آیتم؟ (qty مبنا)')),
                ('max_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد قابل انتخاب')),
            ],
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default_on', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_services', to='products.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='products.service')),
            ],
            options={
                'unique_together': {('product', 'service')},
            },
        ),
        migrations.CreateModel(
            name='CategoryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default_on', models.BooleanField(default=False, verbose_name='پیشنهاد پیش\u200cفرض روشن؟')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_services', to='products.category')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='products.service')),
            ],
            options={
                'unique_together': {('category', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percent_of_item', 'درصدی از قیمت آیتم'), ('per_unit_fixed', 'مبلغ ثابت به ازای هر واحد'), ('tiered_by_item_price', 'پلکانی بر اساس قیمت آیتم')], default='fixed', max_length=40, verbose_name='نوع قیمت')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ/درصد')),
                ('item_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('item_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.service', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'قیمت سرویس',
                'verbose_name_plural': 'قیمت\u200cهای سرویس',
                'indexes': [models.Index(fields=['service', 'is_active'], name='products_se_service_79260b_idx')],
            },
        ),
    ]
