# Generated by Django 5.2.5 on 2025-12-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_service_productservice_categoryservice_serviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='برای محاسبه وزن حجمی؛ اختیاری.', max_digits=6, null=True, verbose_name='ارتفاع بسته (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='برای محاسبه وزن حجمی؛ اختیاری.', max_digits=6, null=True, verbose_name='طول بسته (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_weight_grams',
            field=models.PositiveIntegerField(default=0, help_text='اگر واریانت\u200cها وزن جدا ندارند، وزن ارسال این محصول را اینجا بر حسب گرم وارد کن.', verbose_name='وزن پیش\u200cفرض (گرم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='برای محاسبه وزن حجمی؛ اختیاری.', max_digits=6, null=True, verbose_name='عرض بسته (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False, help_text='برای دوره آنلاین، فایل دانلودی و خدماتی که ارسال پستی ندارند این گزینه را فعال کن.', verbose_name='محصول دیجیتال / بدون ارسال فیزیکی'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_flat_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='برای هر عدد از این کالا، این مقدار به هزینه ارسال اضافه می\u200cشود.', max_digits=12, verbose_name='هزینه بسته\u200cبندی و ارسال (تومان)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ارتفاع (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='طول (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_grams',
            field=models.PositiveIntegerField(default=0, help_text='اگر خالی بماند، از وزن پیش\u200cفرض محصول استفاده می\u200cشود.', verbose_name='وزن این واریانت (گرم)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض (سانتی\u200cمتر)'),
        ),
    ]
