# Generated by Django 5.2.5 on 2025-12-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_default_height_cm_product_default_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_flat_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='برای هر عدد از این کالا، این مقدار به هزینه ارسال اضافه می\u200cشود.', max_digits=12, verbose_name='هزینه بسته\u200cبندی و ارسال (تومان)'),
        ),
    ]
