# Generated by Django 5.2.5 on 2025-12-07 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_shipping_flat_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('base_price', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('source', models.CharField(blank=True, default='auto', help_text='مثلاً admin, script, auto, ...', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.productvariant')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('product', 'variant', 'date')},
            },
        ),
    ]
