# Generated by Django 5.2.5 on 2025-12-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=230, unique=True, verbose_name='اسلاگ'),
        ),
    ]
